# Generated by Django 4.2.23 on 2025-07-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_is_verified_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'верификация', 'verbose_name_plural': 'верификации'},
        ),
    ]
